### ISSUE TITLE
Increase shared memory size

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-docker-images#258]
Reported by @calebrob6, working on the Planetary Computer hub.

Lodging this here for now, but I'm not sure whether it can be solved in pangeo-docker-images, or whether each hub would need to do it.

While training a PyTorch model with multiple workers, he's hitting an error that seems to come from a small shared memory limit

```
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/srv/conda/envs/notebook/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_1394_2747491098>
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/srv/conda/envs/notebook/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_1399_2226946632>
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
```

Listing `/dev/shm` shows it's pretty small (64M).

```
df -hk /dev/shm
Filesystem     1K-blocks  Used Available Use% Mounted on
shm                65536    12     65524   1% /dev/shm
```

I'm trying to figure out now whether this can be set when building, or whether it can only be changed when starting the container (https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container)

https://docs.docker.com/engine/reference/commandline/build/ shows a `--shm-size`, which can be set when building. Perhaps we could set that here?

**Comment by TomAugspurger** [comment]
FYI I was able to work around this at the Kubernetes level in https://github.com/microsoft/planetary-computer-hub/pull/35/files.

I don't think it can be (easily) fixed here until the docker build GitHub action supports the `shm-size` flag that was recently added to buildx.
