### ISSUE TITLE
Using Pangeo ml-notebook with Singularity

### ISSUE THREAD

**Issue by singhakr** [pangeo-data/pangeo-docker-images#429]
I am trying to use the ml-notebook container with singularity on an SLURM cluster. The command I am using for starting Jupyter Notebook is:

singularity exec --nv --cleanenv --bind /home/$USER:/run/user tensorflow.sif jupyter notebook --notebook-dir=/home/$USER --no-browser --ip=0.0.0.0

This command is in a SLURM script, on submitting which with the sbatch command, the job fails with the following error:

```
[I 15:35:55.208 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 656, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/config/application.py", line 1040, in launch_instance
    app.initialize(argv)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook/notebookapp.py", line 2147, in initialize
    self.init_configurables()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook/notebookapp.py", line 1649, in init_configurables
    connection_dir=self.runtime_dir,
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 703, in __get__
    return self.get(obj, cls)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 659, in get
    default = obj.trait_defaults(self.name)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 1872, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/application.py", line 107, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 25, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/srv/conda/envs/notebook/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/srv/conda/envs/notebook/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/srv/conda/envs/notebook/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/srv/conda/envs/notebook/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```

I am new to both SLURM and Singularity. Could you please suggest a solution?

**Comment by rabernat** [comment]
I know that @Marioherreroglez got this image working on Singularity. Mario could do you have any advice?

**Comment by Marioherreroglez** [comment]
Sure! @singhakr, I am not able to reproduce your error but here is my SLURM script so it can serve you as guidance. 

```
#!/bin/sh
#
#SBATCH --account=abernathey     # The account name for the job.
#SBATCH --job-name=jupyter       # The job name.
#SBATCH --gres=gpu:1             # Request 1 gpu (Up to 2 gpus per GPU node)
#SBATCH --partition=ocp_gpu
#SBATCH --constraint=v100s
#SBATCH -c 32                    # The number of cpu cores to use.
#SBATCH --time=0-04:00           # The time the job will take to run in D-HH:MM
#SBATCH --output=/burg/home/$USER/jupyter.log # Important to retrieve the port where the notebook is running, if not included a slurm file with the job-id will be outputted. 

module load singularity

cat /etc/hosts
singularity exec --nv --cleanenv --bind /burg/home/$USER:/run/user tensorflow.sif jupyter notebook --notebook-dir=/burg/home/$USER --no-browser --ip=0.0.0.0
```

Please tell me if the error persists. Maybe sending your SLURM script would be useful for me to have a better understanding of the problem.

**Comment by rabernat** [comment]
@Marioherreroglez - would you be willing to make a PR to add a section about singularity to the Readme.md in this repo?

**Comment by singhakr** [comment]
It seems I was doing binding in the wrong way. With changed binding ($PWD/notebooks:/home/jovyan), the notebook seems to run, but I am now not able to forward ports as it always gives an error.

**Comment by Marioherreroglez** [comment]
> @Marioherreroglez - would you be willing to make a PR to add a section about singularity to the Readme.md in this repo?

I decided to create a separate markdown file that is referenced in the Readme.md, so it does not get too long. [Here](https://github.com/pangeo-data/pangeo-docker-images/pull/430) is the PR.

@singhakr, in this guide I also explain how to forward ports. Hope it solves your problem, if not feel free to add code and error messages.

**Comment by singhakr** [comment]
Yes, this guide will be very helpful. I am doing it in almost the same way, including port forwarding, but I currently have access to only a Windows system, on which I am using an Ubuntu VM WSL. The error may be due to some invalid characters, as the command looks completely correct.

**Comment by singhakr** [comment]
Sometimes I get this error when I try to run the notebook with singularity:
