### ISSUE TITLE
dask labextension cluster launching broken in latest image

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-docker-images#96]
As reported by @cspencerjones on https://discourse.pangeo.io/t/cluster-unknown-address-scheme-error-when-injected-from-sidebar/720

> When I inject a cluster from the sidebar and run I get the following error:
> ValueError: unknown address scheme 'gateway' (known schemes: ['inproc', 'tcp', 'tls', 'ucx'])
>
> (this is again on https://us-central1-b.gcp.pangeo.io/ 1)
> Thanks again!

This is configured here:

https://github.com/pangeo-data/pangeo-docker-images/blob/9b49755dc3b53768a5c3cfc06b7d086a39a599f4/base-image/dask_config.yml#L58-L63

xref: https://github.com/dask/dask-labextension/issues/135

**Comment by scottyhq** [comment]
i'm seeing errors in logs like this on the AWS hub `kubectl logs -n icesat2-prod      dask-gateway-5f8088e361a24ad481cedca5966a2949`

```
distributed.core - ERROR - addresses should be strings or tuples, got None
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/core.py", line 513, in handle_comm
    result = await result
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/scheduler.py", line 2208, in remove_worker
    address = self.coerce_address(address)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/scheduler.py", line 4946, in coerce_address
    raise TypeError("addresses should be strings or tuples, got %r" % (addr,))
TypeError: addresses should be strings or tuples, got None
```

@TomAugspurger ideas? 
maybe related to recent dask version bumps from 2.19 to 2.20

**Comment by scottyhq** [comment]
short term solution i think would be pin to `pangeo/pangeo-image:2020.07.03`

**Comment by TomAugspurger** [comment]
@scottyhq unsure, but the error message is the same as https://github.com/dask/dask/issues/6372. Do you know if the workers are starting successfully, or are the pods terminating? In the linked issue, the worker processes didn't have write permissions to its working directory.

@cspencerjones we'll need to resolve dask/dask-labextension#135 before the labextension button will work with a gateway-based setup.
